# Build the cpdf command line tools and top level
SOURCES = cpdfr.ml

RESULT = cpdfr

PACKS = unix camlpdf

OCAMLNCFLAGS = -g
OCAMLBCFLAGS = -g
OCAMLLDFLAGS = -g

all : native-code

-include OCamlMakefile
